
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftORleftANDAND LPARENT ONEOF OR RPARENT SEMICOLON SEQ f\n    G_user : F1\n           | f\n    \n    F1 : LPARENT F2 RPARENT\n       | ONEOF LPARENT F3 RPARENT\n       | SEQ LPARENT F3 RPARENT\n    \n    F2 : F2 AND F2\n       | F2 OR F2\n       | f\n    \n    F3 : f SEMICOLON F3\n       | f\n    '
    
_lr_action_items = {'f':([0,4,9,10,12,13,20,],[3,8,15,15,8,8,15,]),'LPARENT':([0,5,6,],[4,9,10,]),'ONEOF':([0,],[5,]),'SEQ':([0,],[6,]),'$end':([1,2,3,11,19,21,],[0,-1,-2,-3,-4,-5,]),'RPARENT':([7,8,14,15,16,17,18,22,],[11,-8,19,-10,21,-6,-7,-9,]),'AND':([7,8,17,18,],[12,-8,-6,12,]),'OR':([7,8,17,18,],[13,-8,-6,-7,]),'SEMICOLON':([15,],[20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'G_user':([0,],[1,]),'F1':([0,],[2,]),'F2':([4,12,13,],[7,17,18,]),'F3':([9,10,20,],[14,16,22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> G_user","S'",1,None,None,None),
  ('G_user -> F1','G_user',1,'p_start','grammatica_iniziale.py',46),
  ('G_user -> f','G_user',1,'p_start','grammatica_iniziale.py',47),
  ('F1 -> LPARENT F2 RPARENT','F1',3,'p_F1','grammatica_iniziale.py',52),
  ('F1 -> ONEOF LPARENT F3 RPARENT','F1',4,'p_F1','grammatica_iniziale.py',53),
  ('F1 -> SEQ LPARENT F3 RPARENT','F1',4,'p_F1','grammatica_iniziale.py',54),
  ('F2 -> F2 AND F2','F2',3,'p_F2','grammatica_iniziale.py',59),
  ('F2 -> F2 OR F2','F2',3,'p_F2','grammatica_iniziale.py',60),
  ('F2 -> f','F2',1,'p_F2','grammatica_iniziale.py',61),
  ('F3 -> f SEMICOLON F3','F3',3,'p_F3','grammatica_iniziale.py',66),
  ('F3 -> f','F3',1,'p_F3','grammatica_iniziale.py',67),
]
